### ISSUE TITLE
"No Safari Extensions Certificate"

### ISSUE THREAD

**Issue by cmc18** [alixr/hooktube-safari#1]
When I went to Extensions Builder to install as per your instructions, that warning was in the second line underneath hook.safariextension.

Please advise.
![screen shot hooktubeextbuld](https://user-images.githubusercontent.com/27476775/32138915-06c7cbde-bc0a-11e7-904b-aadf55bf66c6.jpg)

**Comment by alixr** [comment]
It's not necessary unless you are packaging the extension. You can just click install in the top right.
